### ISSUE TITLE
[Osaka Ohsho] Make .osaka-section-title stick to top when it reaches top

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#24]
It should allow the user to scroll through the menu items while still seeing .osaka-section-title in the viewport.

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I am not seeing any navigation to stick

**Comment by janbelmonte** [comment]
This is not a navbar. This is a sidebar with the said class. In browser it says, "OUR FOOD..."

**Comment by RIanDeLaCruz** [comment]
Ohhhhhh. Got it

**Comment by RIanDeLaCruz** [comment]
@janbelmonte something like this?
[Multiple Sticky Titles](http://codepen.io/chrissp26/pen/gBrdo)

**Comment by janbelmonte** [comment]
Yas

**Comment by RIanDeLaCruz** [comment]
Great. I'll be implementing this. HAHA

**Comment by RIanDeLaCruz** [comment]
Could you just style the stuck title? 

CSS: `.osaka-section-title.fixed`

**Comment by janbelmonte** [comment]
Alright, let me take a look.

**Comment by RIanDeLaCruz** [comment]
If this does not work the way you should, I have a jQuery plug-in lined up

**Comment by janbelmonte** [comment]
Working fine, @RIanDeLaCruz, although I have another issue coming up. Just an addition to the script.
