### ISSUE TITLE
[Relish] Navbar items are shown as vertical list (Desktop)

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#27]
![screen shot 2015-11-24 at 11 11 46 pm](https://cloud.githubusercontent.com/assets/9819894/11371001/1ec157de-9301-11e5-9fbb-57951359a4f3.png)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte could you try adding the classes I added to the Relish navigation
