### ISSUE TITLE
[Osaka Ohsho] Add carousel

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#31]
- Carousel should allow fade-in and fade-out of image (see plate of food on upper left portion of attached mockup)
- Carousel should only be contained in its own column (check the code)

![osaka-mockup](https://cloud.githubusercontent.com/assets/9819894/11414121/729e6474-942c-11e5-8d21-d797c6ff15b8.jpg)

**Comment by janbelmonte** [comment]
For your reference:
- http://codepen.io/Rowno/pen/Afykb
- http://codepen.io/alfredk/pen/KsAly

**Comment by janbelmonte** [comment]
![screenshot 2015-11-26 11 03 13](https://cloud.githubusercontent.com/assets/9819894/11414202/7dad0f68-942d-11e5-83ac-05b3347b63ef.png)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte Isn't it better to just cut out the carousel on mobile?

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Ok, I'm good with that!
