### ISSUE TITLE
[Wee Nam Kee] Fix responsiveness of carousel.

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#40]
Looks ok when on desktop and mobile but gets messy when you resize in between (tablet etc). Please fix if you have time.

**Comment by RIanDeLaCruz** [comment]
What kind of messy?

**Comment by janbelmonte** [comment]
Oh, I fixed this na pala. Can you just make the relish logo layer on top of the carousel images? Ty

Sent from Mobile




On Thu, Dec 17, 2015 at 6:10 PM -0800, "Ian De La Cruz" <notifications@github.com> wrote:












What kind of messy?

**Comment by RIanDeLaCruz** [comment]
The overlay seems to be a Chrome bug.

it appears perfectly on Firefox

**Comment by janbelmonte** [comment]
Hmm, okay. Will leave this issue here until we find a solution.

**Comment by janbelmonte** [comment]
Will do a fresh set of issues over at BitBucket.
