### ISSUE TITLE
[Kumori] Add script that detects vertical scrollbar and changes menu item width

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#43]
This might help: https://web-design-weekly.com/2014/11/18/viewport-units-vw-vh-vmin-vmax/

**Comment by RIanDeLaCruz** [comment]
Could you explain this better?

**Comment by janbelmonte** [comment]
Notice in the menu that the scrollbar becomes a problem for the width of the menu items.

Sent from Mobile




On Thu, Dec 17, 2015 at 6:11 PM -0800, "Ian De La Cruz" <notifications@github.com> wrote:












Could you explain this better?

**Comment by RIanDeLaCruz** [comment]
Could you take screenshots of this

**Comment by janbelmonte** [comment]
It's like 1px on desktop

![screenshot 2015-12-22 23 56 32](https://cloud.githubusercontent.com/assets/9819894/11959353/c7b40a32-a907-11e5-9eb1-aff97ed60dfe.png)

**Comment by janbelmonte** [comment]
Closing this since it doesn't seem to be a significant issue.
