### ISSUE TITLE
[Relish] How do we signify that contact form submission has been sent?

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#44]

**Comment by RIanDeLaCruz** [comment]
We could add a simple span at the bottom of the form upon submission.

**Comment by janbelmonte** [comment]
@RIanDeLaCruz Alright, kindly implement a simple success message. :)

**Comment by janbelmonte** [comment]
Just realized that we're bound to replace this once we convert to Wordpress, so this is a temporary solution.

**Comment by RIanDeLaCruz** [comment]
Pwede na hindi siya temporary solution. Moving it to WP wouldn't really make a lot of difference
