### ISSUE TITLE
[Kumori] Make menu item descriptions visible on click

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#45]
Right now, menu item descriptions are only visible on hover. We need them to be visible when people tap them on mobile.

This might help: https://css-tricks.com/forums/topic/click-function-for-hover-states-on-touch-devices/

**Comment by RIanDeLaCruz** [comment]
They appear on tap on my phone

**Comment by janbelmonte** [comment]
Unfortunately not for iPhones. Our client's an iPhone user.

**Comment by RIanDeLaCruz** [comment]
http://slickmedia.co.uk/blog/glenns-blog/fix-ipad-iphone-css-hover-issues/
