### ISSUE TITLE
[Osaka Ohsho] Convert to WP

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#54]
Carousel images
Menu items (food type, food name, price, + optional photo—to be discussed)
Branches (area, address, number)

**Comment by RIanDeLaCruz** [comment]
@janbelmonte I am having difficulties with converting this to a template.

There are certain menu items that aren't on a one-to-one relation with a single `<td>`.

![image](https://cloud.githubusercontent.com/assets/7766185/12090886/a98dc040-b32d-11e5-8e1c-50af422c56be.png)

My suggestion would be to denote the food category with a `<th>` and to put sub-items in a nested `table`
[SEE THIS](http://stackoverflow.com/questions/17088868/html-table-tr-inside-td)

**Comment by janbelmonte** [comment]
Makes sense. 
Alternate idea: would it be possible to just make custom post/html fields for the two divs (one for each column) so we can just copy paste the table into a text editor? 

That way, it would be easier to edit menu items and the styling would be handled by our set styles. Would that work?

Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 998 866 7690
www.janbelmonte.com




On Mon, Jan 4, 2016 at 6:05 AM -0800, "Ian De La Cruz" <notifications@github.com> wrote:












@janbelmonte I am having difficulties with converting this to a template.



There are certain menu items that aren't on a one-to-one relation with a single <td>.







My suggestion would be to denote the food category with a <th> and to put sub-items in a nested table

SEE THIS

**Comment by RIanDeLaCruz** [comment]
I can't visualize what you're trying to say. Also, what do we expect them to do when they add menu items? This is important to know.

**Comment by RIanDeLaCruz** [comment]
Here's what I've in mind.

Headers should really be in `<th>`. 
For menu items, such as Original Gyoza, Chesse Gyoza, and the like, we could add a custom field where they have a comma-separated list of all sub-items (6pcs, 12pcs, etc). Sub-items would follow the format: ```Sub-Item_Price,Sub-Item_Price```

For every post, there will be a notes custom field. I am still thinking of the possible input pattern.

________________________________________________

Another option would be for me to create a new Post Type, though that MIGHT be overkill.

**Comment by janbelmonte** [comment]
I'm generally okay with your proposed solution as long as it's easy to work with.
For my alternate idea, imagine assigning two posts that will show up in the menu area. One post is for the left column, another is for the right column. Each post will just be edited everytime there are updates to the menu. Edits can be made by editing the table in the editor. Just an idea but I'm not sure if it's feasible.

Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 998 866 7690
www.janbelmonte.com




On Mon, Jan 4, 2016 at 6:45 AM -0800, "Ian De La Cruz" <notifications@github.com> wrote:












Here's what I've in mind.



Headers should really be in <th>. 

For menu items, such as Original Gyoza, Chesse Gyoza, and the like, we could add a custom field where they have a comma-separated list of all sub-items (6pcs, 12pcs, etc). Sub-items would follow the format: Sub-Item_Price,Sub-Item_Price



For every post, there will be a notes custom field. I am still thinking of the possible input pattern.





Another option would be for me to create a new Post Type, though that MIGHT be overkill.

**Comment by RIanDeLaCruz** [comment]
ahhh, so kakaiba yung custom field na mangyayari. I doubt that there exists an easy implementation for that.

**Comment by janbelmonte** [comment]
Okay, just checked. You can go ahead with your idea. Although how would a user go about editing the menu?

Sent from Mobile

Jan-Daniel S. Belmonte
Graphic Designer

(+63) 998 866 7690
www.janbelmonte.com




On Mon, Jan 4, 2016 at 6:59 AM -0800, "Ian De La Cruz" <notifications@github.com> wrote:












ahhh, so kakaiba yung custom field na mangyayari. I doubt that there exists an easy implementation for that.
