### ISSUE TITLE
[Kumori] Nav ul should appear as a single row under navbar on mobile and tablet

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#7]
Should only be inside navbar when @media (min-width: 750px)
No need for hamburger icon.

![screenshot 2015-11-22 11 47 00](https://cloud.githubusercontent.com/assets/9819894/11321969/6a327aac-910f-11e5-987a-844e73821413.png)

**Comment by RIanDeLaCruz** [comment]
Please explain this @janbelmonte

**Comment by janbelmonte** [comment]
@riandelacruz basically, make the nav responsive

**Comment by RIanDeLaCruz** [comment]
And the relish group image ang maging icon?

**Comment by janbelmonte** [comment]
Ah! I remember what I meant here na. Make the nav list one row underneath the big navbar. So there won't be any need for an icon anymore.

**Comment by janbelmonte** [comment]
Whoops, accidentally closed. Please work on this, @RIanDeLaCruz!

**Comment by RIanDeLaCruz** [comment]
Could you sketch it out?
