### ISSUE TITLE
[Relish] x (close) button in #brand-bar is missing on mobile

### ISSUE THREAD

**Issue by janbelmonte** [janbelmonte/Relish-Group#8]
![screenshot 2015-11-22 16 07 26](https://cloud.githubusercontent.com/assets/9819894/11322699/536471a8-9133-11e5-9518-4eda5bb06ace.png)

**Comment by RIanDeLaCruz** [comment]
Has been fixed. Forgot to put into the commit logs

**Comment by janbelmonte** [comment]
Whoops, accidentally closed. Please work on this, @RIanDeLaCruz!

**Comment by janbelmonte** [comment]
GRR commented on the wrong issue
